language: node_js

before_script:
 npm install -g ionic cordova
 npm install
script:
 ionic cordova build browser — prod
 ionic serve
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN 
 keep-history: true
 on:
   branch: master
 local_dir: www
